site_name: Megham 
site_url: https://skhrg.github.io/megham/
theme: material 
plugins:
  - search
  - mkdocs-homepage-copier
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
extra:
  version:
    provider: mike
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: 'index.md'
  - Joint CPD: "joint_cpd.md"
  - API Reference: reference/
